site_name: BOS documentation
site_url: https://mydomain.org/

nav:
  - Introduction: 'index.md'
  - Services:
      - 'services/index.md'
      - 'services/api.md'
theme:
  name: material
  language: en
  #  logo: assets/logo.png
  #  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.instant.progress
    - content.code.copy # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#__codelineno-0-8
    - content.code.select
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  font:
    text: Roboto
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
#extra:
#  consent:
#    title: Cookie consent
#    description: >-
#      We use cookies to recognize your repeated visits and preferences, as well
#      as to measure the effectiveness of our documentation and whether users
#      find what they're searching for. With your consent, you're helping us to
#      make our documentation better.
extra:
  generator: false

copyright: Copyright &copy; 2024 - Roberto Chiosa
repo_url: https://github.com/RobertoChiosa/building-operating-system
repo_name: building-operating-system

# https://squidfunk.github.io/mkdocs-material/reference/diagrams/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  # https://squidfunk.github.io/mkdocs-material/reference/grids/
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

