version: '3.8'
services:
  db: # database service
    container_name: db
    image: timescale/timescaledb-ha:pg16 # use official postgres image
    restart: unless-stopped
    environment: # define environment variables
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: # mount local directory to container
      - ./postgres:/docker-entrypoint-initdb.d
    ports: # expose ports
      - 5432:5432
  graphdb:
    container_name: graphdb
    image: ontotext/graphdb:10.7.2
    restart: unless-stopped
    ports:
      - 7200:7200
      - 7300:7300
    environment:
      GDB_JAVA_OPTS: >-
        -Xmx4g -Xms4g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
    volumes:
      - ./graphdb/graphdb-data:/opt/graphdb/home
  api: # API service
    container_name: api
    build: ./api/ # path to service's Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
#    depends_on: # explicitly define dependency
#      - db
#      - graphdb
volumes:
  postgres-data:
