version: '3.8'
services:
  db: # database service
    container_name: db
    image: postgres:latest # use official postgres image
    environment: # define environment variables
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: monitoring
    volumes: # mount local directory to container
      - ./postgres:/docker-entrypoint-initdb.d
    ports: # expose ports
      - 5432:5432
    restart: always # restart policy
  api: # API service
    build: ./api/ # path to service's Dockerfile
    container_name: api
    ports:
      - 8000:8000
    depends_on: # explicitly define dependency
      - db
volumes:
  postgres-data:
