version: '3.8'
services:
  api:
    build: ./api/
    ports:
      - 8000:8000
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres-data:
